# Generated by Django 5.2.4 on 2025-07-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE users_supplierprofile DROP COLUMN IF EXISTS role;",
            reverse_sql="ALTER TABLE users_supplierprofile ADD COLUMN role varchar(20) NOT NULL DEFAULT 'client';"
        ),
    ]
