# Generated by Django 5.2.4 on 2025-07-06 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название магазина', max_length=255)),
                ('description', models.TextField(help_text='Описание магазина')),
                ('is_active', models.BooleanField(default=True, help_text='Принимает ли магазин заказы')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания магазина')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления магазина')),
                ('supplier', models.ForeignKey(help_text='Поставщик', on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='users.supplierprofile')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['-created_at'],
            },
        ),
    ]
